.TH "BASS_DX8_COMPRESSOR" 3 "Thu Jun 18 2015" "Version v.2" "Voice analyze" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BASS_DX8_COMPRESSOR \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBfGain\fP"
.br
.ti -1c
.RI "float \fBfAttack\fP"
.br
.ti -1c
.RI "float \fBfRelease\fP"
.br
.ti -1c
.RI "float \fBfThreshold\fP"
.br
.ti -1c
.RI "float \fBfRatio\fP"
.br
.ti -1c
.RI "float \fBfPredelay\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Voice analyze from the source code\&.
