.TH "BASS_DX8_CHORUS" 3 "Thu Jun 18 2015" "Version v.2" "Voice analyze" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BASS_DX8_CHORUS \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBfWetDryMix\fP"
.br
.ti -1c
.RI "float \fBfDepth\fP"
.br
.ti -1c
.RI "float \fBfFeedback\fP"
.br
.ti -1c
.RI "float \fBfFrequency\fP"
.br
.ti -1c
.RI "DWORD \fBlWaveform\fP"
.br
.ti -1c
.RI "float \fBfDelay\fP"
.br
.ti -1c
.RI "DWORD \fBlPhase\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Voice analyze from the source code\&.
