.TH "BASS_FILEPROCS" 3 "Thu Jun 18 2015" "Version v.2" "Voice analyze" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BASS_FILEPROCS \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "FILECLOSEPROC * \fBclose\fP"
.br
.ti -1c
.RI "FILELENPROC * \fBlength\fP"
.br
.ti -1c
.RI "FILEREADPROC * \fBread\fP"
.br
.ti -1c
.RI "FILESEEKPROC * \fBseek\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Voice analyze from the source code\&.
