.TH "BASS_INFO" 3 "Thu Jun 18 2015" "Version v.2" "Voice analyze" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BASS_INFO \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "DWORD \fBflags\fP"
.br
.ti -1c
.RI "DWORD \fBhwsize\fP"
.br
.ti -1c
.RI "DWORD \fBhwfree\fP"
.br
.ti -1c
.RI "DWORD \fBfreesam\fP"
.br
.ti -1c
.RI "DWORD \fBfree3d\fP"
.br
.ti -1c
.RI "DWORD \fBminrate\fP"
.br
.ti -1c
.RI "DWORD \fBmaxrate\fP"
.br
.ti -1c
.RI "BOOL \fBeax\fP"
.br
.ti -1c
.RI "DWORD \fBminbuf\fP"
.br
.ti -1c
.RI "DWORD \fBdsver\fP"
.br
.ti -1c
.RI "DWORD \fBlatency\fP"
.br
.ti -1c
.RI "DWORD \fBinitflags\fP"
.br
.ti -1c
.RI "DWORD \fBspeakers\fP"
.br
.ti -1c
.RI "DWORD \fBfreq\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Voice analyze from the source code\&.
