.TH "BASS_SAMPLE" 3 "Thu Jun 18 2015" "Version v.2" "Voice analyze" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BASS_SAMPLE \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "DWORD \fBfreq\fP"
.br
.ti -1c
.RI "float \fBvolume\fP"
.br
.ti -1c
.RI "float \fBpan\fP"
.br
.ti -1c
.RI "DWORD \fBflags\fP"
.br
.ti -1c
.RI "DWORD \fBlength\fP"
.br
.ti -1c
.RI "DWORD \fBmax\fP"
.br
.ti -1c
.RI "DWORD \fBorigres\fP"
.br
.ti -1c
.RI "DWORD \fBchans\fP"
.br
.ti -1c
.RI "DWORD \fBmingap\fP"
.br
.ti -1c
.RI "DWORD \fBmode3d\fP"
.br
.ti -1c
.RI "float \fBmindist\fP"
.br
.ti -1c
.RI "float \fBmaxdist\fP"
.br
.ti -1c
.RI "DWORD \fBiangle\fP"
.br
.ti -1c
.RI "DWORD \fBoangle\fP"
.br
.ti -1c
.RI "float \fBoutvol\fP"
.br
.ti -1c
.RI "DWORD \fBvam\fP"
.br
.ti -1c
.RI "DWORD \fBpriority\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Voice analyze from the source code\&.
