.TH "BASS_PLUGININFO" 3 "Thu Jun 18 2015" "Version v.2" "Voice analyze" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BASS_PLUGININFO \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "DWORD \fBversion\fP"
.br
.ti -1c
.RI "DWORD \fBformatc\fP"
.br
.ti -1c
.RI "const \fBBASS_PLUGINFORM\fP * \fBformats\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Voice analyze from the source code\&.
