.TH "BASS_DX8_I3DL2REVERB" 3 "Thu Jun 18 2015" "Version v.2" "Voice analyze" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BASS_DX8_I3DL2REVERB \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBlRoom\fP"
.br
.ti -1c
.RI "int \fBlRoomHF\fP"
.br
.ti -1c
.RI "float \fBflRoomRolloffFactor\fP"
.br
.ti -1c
.RI "float \fBflDecayTime\fP"
.br
.ti -1c
.RI "float \fBflDecayHFRatio\fP"
.br
.ti -1c
.RI "int \fBlReflections\fP"
.br
.ti -1c
.RI "float \fBflReflectionsDelay\fP"
.br
.ti -1c
.RI "int \fBlReverb\fP"
.br
.ti -1c
.RI "float \fBflReverbDelay\fP"
.br
.ti -1c
.RI "float \fBflDiffusion\fP"
.br
.ti -1c
.RI "float \fBflDensity\fP"
.br
.ti -1c
.RI "float \fBflHFReference\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Voice analyze from the source code\&.
