.TH "QCPAxisPainterPrivate::TickLabelData" 3 "Thu Jun 18 2015" "Version v.2" "Voice analyze" \" -*- nroff -*-
.ad l
.nh
.SH NAME
QCPAxisPainterPrivate::TickLabelData \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "QString \fBbasePart\fP"
.br
.ti -1c
.RI "QString \fBexpPart\fP"
.br
.ti -1c
.RI "QRect \fBbaseBounds\fP"
.br
.ti -1c
.RI "QRect \fBexpBounds\fP"
.br
.ti -1c
.RI "QRect \fBtotalBounds\fP"
.br
.ti -1c
.RI "QRect \fBrotatedTotalBounds\fP"
.br
.ti -1c
.RI "QFont \fBbaseFont\fP"
.br
.ti -1c
.RI "QFont \fBexpFont\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Voice analyze from the source code\&.
