.TH "RGB" 3 "Thu Jun 18 2015" "Version v.2" "Voice analyze" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RGB \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "qint8 \fBrgbRed\fP"
.br
.ti -1c
.RI "qint8 \fBrgbGreen\fP"
.br
.ti -1c
.RI "qint8 \fBrgbBlue\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Voice analyze from the source code\&.
