.TH "TAG_CART" 3 "Thu Jun 18 2015" "Version v.2" "Voice analyze" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TAG_CART \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char \fBVersion\fP [4]"
.br
.ti -1c
.RI "char \fBTitle\fP [64]"
.br
.ti -1c
.RI "char \fBArtist\fP [64]"
.br
.ti -1c
.RI "char \fBCutID\fP [64]"
.br
.ti -1c
.RI "char \fBClientID\fP [64]"
.br
.ti -1c
.RI "char \fBCategory\fP [64]"
.br
.ti -1c
.RI "char \fBClassification\fP [64]"
.br
.ti -1c
.RI "char \fBOutCue\fP [64]"
.br
.ti -1c
.RI "char \fBStartDate\fP [10]"
.br
.ti -1c
.RI "char \fBStartTime\fP [8]"
.br
.ti -1c
.RI "char \fBEndDate\fP [10]"
.br
.ti -1c
.RI "char \fBEndTime\fP [8]"
.br
.ti -1c
.RI "char \fBProducerAppID\fP [64]"
.br
.ti -1c
.RI "char \fBProducerAppVersion\fP [64]"
.br
.ti -1c
.RI "char \fBUserDef\fP [64]"
.br
.ti -1c
.RI "DWORD \fBdwLevelReference\fP"
.br
.ti -1c
.RI "\fBTAG_CART_TIMER\fP \fBPostTimer\fP [8]"
.br
.ti -1c
.RI "char \fBReserved\fP [276]"
.br
.ti -1c
.RI "char \fBURL\fP [1024]"
.br
.ti -1c
.RI "char \fBTagText\fP []"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Voice analyze from the source code\&.
