.TH "TAG_CART_TIMER" 3 "Thu Jun 18 2015" "Version v.2" "Voice analyze" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TAG_CART_TIMER \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "DWORD \fBdwUsage\fP"
.br
.ti -1c
.RI "DWORD \fBdwValue\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Voice analyze from the source code\&.
