.TH "TAG_BEXT" 3 "Thu Jun 18 2015" "Version v.2" "Voice analyze" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TAG_BEXT \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char \fBDescription\fP [256]"
.br
.ti -1c
.RI "char \fBOriginator\fP [32]"
.br
.ti -1c
.RI "char \fBOriginatorReference\fP [32]"
.br
.ti -1c
.RI "char \fBOriginationDate\fP [10]"
.br
.ti -1c
.RI "char \fBOriginationTime\fP [8]"
.br
.ti -1c
.RI "QWORD \fBTimeReference\fP"
.br
.ti -1c
.RI "WORD \fBVersion\fP"
.br
.ti -1c
.RI "BYTE \fBUMID\fP [64]"
.br
.ti -1c
.RI "BYTE \fBReserved\fP [190]"
.br
.ti -1c
.RI "char \fBCodingHistory\fP []"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Voice analyze from the source code\&.
