.TH "tWAVEFORMATEX" 3 "Thu Jun 18 2015" "Version v.2" "Voice analyze" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tWAVEFORMATEX \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "WORD \fBwFormatTag\fP"
.br
.ti -1c
.RI "WORD \fBnChannels\fP"
.br
.ti -1c
.RI "DWORD \fBnSamplesPerSec\fP"
.br
.ti -1c
.RI "DWORD \fBnAvgBytesPerSec\fP"
.br
.ti -1c
.RI "WORD \fBnBlockAlign\fP"
.br
.ti -1c
.RI "WORD \fBwBitsPerSample\fP"
.br
.ti -1c
.RI "WORD \fBcbSize\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Voice analyze from the source code\&.
